import React from 'react';
import {motion, useScroll, useTransform, useSpring} from 'framer-motion';
import {ArrowUpRight, ArrowDown, Waves, ScanEye, Fingerprint, Activity, Cpu, ChevronRight, Droplets, Menu, X} from 'lucide-react';

const M = motion;
const fade = {hidden:{opacity:0,y:55},visible:{opacity:1,y:0,transition:{duration:.85,ease:[.22,1,.36,1]}}};
const ocean='https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=2000&q=85';
const underwater='https://images.unsplash.com/photo-1546026423-cc4642628d2b?w=2000&q=85';
const wave='https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1400&q=85';
const coral='https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=85';
const sea='https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=85';
function Reveal({children,className='',delay=0}){return <M.div className={className} variants={fade} initial="hidden" whileInView="visible" viewport={{once:true,amount:.16}} transition={{delay}}>{children}</M.div>}
function Nav(){const [open,setOpen]=React.useState(false);return <nav className="nav"><a className="logo" href="#top"><span className="logo-mark"><Waves size={22}/></span>AquaLens<span className="logo-ai">AI</span></a><div className={'nav-links '+(open?'show':'')}><a href="#story" onClick={()=>setOpen(false)}>Overview</a><a href="#science" onClick={()=>setOpen(false)}>Our Science</a><a href="#fingerprint" onClick={()=>setOpen(false)}>Fingerprint</a><a href="#dashboard" onClick={()=>setOpen(false)}>Dashboard</a></div><a className="nav-cta" href="#dashboard">Explore platform <ArrowUpRight size={14}/></a><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></nav>}
function Hero(){const ref=React.useRef(null);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const titleY=useTransform(scrollYProgress,[0,1],[0,180]);const waterY=useTransform(scrollYProgress,[0,1],[0,-140]);const opacity=useTransform(scrollYProgress,[0,.9],[1,0]);return <section className="hero" id="top" ref={ref}><M.div className="hero-photo" style={{backgroundImage:`linear-gradient(180deg,rgba(5,29,48,.16),rgba(1,21,36,.14) 40%,rgba(1,22,37,.93)),url('${underwater}')`,y:waterY}}/><div className="hero-toplight"/><Nav/><M.div className="hero-center" style={{y:titleY,opacity}}><div className="hero-eyebrow"><span className="pulse"/> THE FUTURE OF WATER INTELLIGENCE</div><h1>AQUA<span>LENS</span></h1><div className="hero-sub">SEE BEYOND THE SURFACE</div><p>Every water source has a story.<br/>We're learning how to read it.</p><a className="outline-button" href="#story">Dive into AquaLens <ArrowDown size={16}/></a></M.div><div className="waterline"/><div className="hero-bottom"><span>01 / THE BEGINNING</span><span>SCROLL TO EXPLORE <ArrowDown size={14}/></span><span>VISUAL WATER INTELLIGENCE</span></div></section>}
function Story(){return <section id="story" className="story section-pad"><div className="section-shell story-grid"><Reveal><div className="eyebrow">01 / THE VISION</div><h2>Water tells us<br/><em>more than we see.</em></h2><p className="lead">Most monitoring systems measure water at a moment in time. AquaLens explores what happens when we start understanding its visual identity over time.</p><p className="muted">Through computer vision and machine learning, we translate colour, texture, and structural patterns into meaningful, interpretable information — building toward source-specific water monitoring.</p><a className="text-link" href="#science">Discover the approach <ArrowUpRight size={17}/></a></Reveal><Reveal className="story-photo"><img src={wave} alt="Ocean wave seen from above"/><div className="photo-label"><span>BEYOND A SINGLE MEASUREMENT</span><Waves size={22}/></div></Reveal></div><div className="numbers section-shell"><Reveal><strong>6,515</strong><span>WATER IMAGES</span></Reveal><Reveal><strong>20</strong><span>VISUAL FEATURES</span></Reveal><Reveal><strong>83.38%</strong><span>TEST ACCURACY</span></Reveal><Reveal><strong>03</strong><span>VISUAL CLASSES</span></Reveal></div></section>}
const steps=[{num:'01',icon:ScanEye,title:'Observe',desc:'Capture and preprocess water imagery under consistent conditions.',image:sea},{num:'02',icon:Activity,title:'Understand',desc:'Extract 20 descriptors of colour, texture, and structure.',image:coral},{num:'03',icon:Fingerprint,title:'Recognize',desc:'Classify visual conditions and build toward source-specific fingerprints.',image:wave}];
function Science(){return <section id="science" className="science section-pad"><div className="section-shell"><Reveal className="center-head"><div className="eyebrow">02 / WHAT WE DO</div><h2>From pixels<br/>to <em>perspective.</em></h2><p>Three layers of visual intelligence. One clearer understanding of water.</p></Reveal><div className="science-cards">{steps.map((s,i)=><Reveal key={s.num} className="science-card"><div className="science-image" style={{backgroundImage:`linear-gradient(180deg,transparent 10%,rgba(1,17,30,.8)),url('${s.image}')`}}/><div className="science-content"><span>{s.num} / INTELLIGENCE LAYER</span><s.icon size={27} strokeWidth={1.5}/><h3>{s.title}</h3><p>{s.desc}</p><div className="science-rule"><ArrowUpRight size={19}/></div></div></Reveal>)}</div></div></section>}
function FingerprintSection(){const ref=React.useRef(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const y=useTransform(scrollYProgress,[0,1],[-70,80]);return <section id="fingerprint" className="fingerprint" ref={ref}><M.div className="fingerprint-bg" style={{backgroundImage:`linear-gradient(90deg,rgba(1,19,31,.95),rgba(1,25,40,.45)),url('${underwater}')`,y}}/><div className="section-shell fingerprint-inner"><Reveal><div className="eyebrow">03 / THE NEXT FRONTIER</div><h2>Every source.<br/><em>A signature of its own.</em></h2><p>Imagine a visual fingerprint unique to a lake, river, or reservoir — one that can be compared with future observations to detect meaningful changes.</p><div className="future-pill"><span className="pulse"/> RESEARCH DIRECTION · OBJECTIVE 3</div></Reveal><Reveal className="fingerprint-graphic"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="orbit-center"><Fingerprint size={82} strokeWidth={.75}/></div><div className="orbit-caption">SOURCE-SPECIFIC VISUAL IDENTITY</div></Reveal></div></section>}
function Dashboard(){return <section id="dashboard" className="dashboard section-pad"><div className="section-shell"><Reveal className="center-head"><div className="eyebrow">04 / THE EXPERIENCE</div><h2>Clarity, at<br/><em>every depth.</em></h2><p>An interface designed to turn complex visual signals into an understandable picture.</p></Reveal><Reveal className="dashboard-frame"><div className="dash-nav"><span className="dash-brand"><Waves size={17}/> AquaLens <b>AI</b></span><span>OVERVIEW <i/> ANALYSIS <i/> FINGERPRINTS</span><span className="dash-status"><span className="pulse"/> RESEARCH PREVIEW</span></div><div className="dash-body"><div className="dash-heading"><div><small>WATER INTELLIGENCE / OVERVIEW</small><h3>See what the water is saying.</h3></div><div className="dash-date">DEMO INTERFACE <ArrowUpRight size={16}/></div></div><div className="dash-grid"><div className="dash-stat"><small>MODEL TEST ACCURACY</small><strong>83.38<span>%</span></strong><p>Random Forest · O2</p></div><div className="dash-stat"><small>VISUAL FEATURES</small><strong>20</strong><p>Optimized representation</p></div><div className="dash-stat"><small>VISUAL CATEGORIES</small><strong>03</strong><p>Low / Medium / High</p></div><div className="dash-stat future"><small>SOURCE BASELINE</small><strong>—</strong><p>Planned · Objective 3</p></div></div><div className="dash-bottom"><div className="dash-visual"><div className="dash-visual-head">FEATURE REPRESENTATION <span>20 DIMENSIONS</span></div><div className="bars">{[35,58,44,74,53,87,67,49,81,56,70,43,61,78,52,66,40,73,57,46].map((v,i)=><M.div key={i} initial={{height:0}} whileInView={{height:`${v}%`}} viewport={{once:true}} transition={{duration:.8,delay:i*.035}}/>)}</div><small>ILLUSTRATIVE VISUALIZATION · NOT LIVE DATA</small></div><div className="dash-map"><div className="dash-visual-head">SAMPLE PREVIEW <span>RGB IMAGERY</span></div><img src={coral} alt="Underwater sample preview"/><div className="dash-map-footer"><span>Visual analysis pipeline</span><ChevronRight size={16}/></div></div></div></div></Reveal><Reveal className="after-dashboard"><p>Built for research. Designed for discovery.</p><a className="outline-button" href="#top">Back to the surface <ArrowUpRight size={16}/></a></Reveal></div></section>}
function Footer(){return <footer><div className="section-shell footer-grid"><div><div className="footer-brand"><Waves/> AquaLens AI</div><p>Water Fingerprinting & Intelligent Quality Monitoring</p></div><div className="footer-right"><span>AN EXPLORATION IN VISUAL WATER INTELLIGENCE</span><span>© 2026 AQUALENS AI</span></div></div></footer>}
function App(){return <><Hero/><Story/><Science/><FingerprintSection/><Dashboard/><Footer/></>};
export default App;
